version: "3.0"

services:
  app:
    container_name: flashlet-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=${PORT}
      - MONGO_HOST=mongodb
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_DB}
      - JWT_SECRET=${JWT_SECRET}
      - RESET_PASSWORD_SECRET=${RESET_PASSWORD_SECRET}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - CLOUD_NAME=${CLOUD_NAME}
      - CLOUD_KEY=${CLOUD_KEY}
      - CLOUD_SECRET=${CLOUD_SECRET}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - "${PORT}:${PORT}"
    restart: "unless-stopped"
    depends_on:
      - mongodb
      - redis
  
  mongodb:
    container_name: flashlet-mongo
    image: mongo
    volumes:
      - ./docker/data/db:/data/db
    ports:
      - "27017:27017"
    restart: "unless-stopped"
  
  redis:
    container_name: flashlet-redis
    image: redis:5.0-alpine
    volumes:
      - ./docker/data/redis:/data
    ports:
      - "6379:6379"
    restart: "unless-stopped"
